<?php

/**
 * Implements hook_environment_indicator_matched_indicator_alter().
 */
function devinci_environment_indicator_matched_indicator_alter(&$env) {
  // Base the indicator on our own settings.
  // that use the environment module.
  if (!defined('ENVIRONMENT')) {
    $env['name'] = 'unknown';
    return;
  }

  $real_env = ENVIRONMENT;
  $env['name'] = $real_env;
  switch ($real_env) {
    case 'local':
      $env['color'] = '#208f00';
      break;

    case 'development':
      $env['color'] = '#e07a00';
      break;

    case 'test':
      $env['color'] = '#c41e02';
      break;

    case 'production':
      $env['color'] = '#5e5e5e';
      break;
  }
}

/**
 * Implementation of hook_environment_switch().
 */
function devinci_environment_switch($target_env, $current_env) {
  // Developers can define this function in settings.php and it will be called.
  if (function_exists('devinci_custom_environment_switch')) {
    devinci_custom_environment_switch($target_env, $current_env);
  }
  // TODO: additional devinci specific things to change on env change.
}
