environment.admin_settings:
  path: /admin/config/system/environment
  defaults:
    _title: Environment
    _form: \Drupal\environment\Form\EnvironmentAdminSettings
  requirements:
    _permission: 'administer site configuration'
environment.switch_confirm:
  path: /admin/config/system/environment/switch/%environment
  defaults:
    _title: 'Environment Switch'
    _form: \Drupal\environment\Form\EnvironmentSwitchConfirm
  requirements:
    _permission: 'administer site configuration'

# Environment routing definition
entity.environment.collection:
  path: '/admin/structure/environment'
  defaults:
    _entity_list: 'environment'
    _title: 'Environment'
  requirements:
    _permission: 'administer site configuration'

entity.environment.add_form:
  path: '/admin/structure/environment/add'
  defaults:
    _entity_form: 'environment.add'
    _title: 'Add Environment'
  requirements:
    _permission: 'administer site configuration'

entity.environment.edit_form:
  path: '/admin/structure/environment/{environment}'
  defaults:
    _entity_form: 'environment.edit'
    _title: 'Edit Environment'
  requirements:
    _permission: 'administer site configuration'

entity.environment.delete_form:
  path: '/admin/structure/environment/{environment}/delete'
  defaults:
    _entity_form: 'environment.delete'
    _title: 'Delete Environment'
  requirements:
    _permission: 'administer site configuration'
