environment.admin_settings:
  route_name: environment.admin_settings
  title: Environment
  description: 'Settings for Environment.'
  parent: system.admin_config_system
environment.switch_confirm:
  route_name: environment.switch_confirm
  title: 'Environment Switch'
  description: 'Switch the current environment.'
# Environment menu items definition
entity.environment.collection:
  title: 'Environment'
  route_name: entity.environment.collection
  description: 'List Environment'
  parent: system.admin_structure
