name: Environment
description: 'Sets the environment variable for a site instance'
# core: 8.x
type: module

# Information added by Drupal.org packaging script on 2015-08-17
version: '8.x-1.x-dev'
core: '8.x'
project: 'environment'
datestamp: 1439832241
